# Generated by Django 3.0.6 on 2021-12-19 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('engine_type', models.CharField(max_length=30)),
                ('pollutant_class', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('sold', 'Sold')], default='in_stock', max_length=20)),
                ('door', models.CharField(max_length=20)),
                ('capacity', models.CharField(max_length=25)),
                ('gear_case', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('slug', models.CharField(max_length=20)),
                ('sitting_place', models.IntegerField()),
                ('first_registration_date', models.DateTimeField()),
                ('engine_power', models.CharField(max_length=20)),
                ('other', models.TextField()),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=15)),
                ('metadata', models.CharField(max_length=15)),
                ('url', models.URLField()),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='CarProperty',
            fields=[
                ('car_property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car')),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Property')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Color'),
        ),
        migrations.AddField(
            model_name='car',
            name='dealer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Model'),
        ),
    ]
