# Generated by Django 3.0.6 on 2021-12-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211219_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('fuel_type', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gas', 'Gas'), ('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('electro', 'Electro')], default='diesel', max_length=40, verbose_name='Fuel type')),
                ('fuel_type_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car')),
            ],
            options={
                'verbose_name': 'Fuel type',
                'verbose_name_plural': 'Fuel types',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.FuelType'),
        ),
    ]
