# Generated by Django 3.0.6 on 2021-12-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20211225_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='fuel_type_id',
        ),
        migrations.RemoveField(
            model_name='fueltype',
            name='fuel_type_car_id',
        ),
        migrations.RemoveField(
            model_name='fueltype',
            name='fuel_type_id',
        ),
        migrations.RemoveField(
            model_name='fueltype',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.FuelType'),
        ),
        migrations.AddField(
            model_name='fueltype',
            name='fuel_type',
            field=models.CharField(choices=[('gas', 'Gas'), ('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('electro', 'Electro')], default='diesel', max_length=40),
        ),
        migrations.AddField(
            model_name='fueltype',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
