# Generated by Django 3.0.6 on 2021-12-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20211225_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fuel',
            new_name='fuel_id',
        ),
    ]
