# Generated by Django 3.0.6 on 2021-12-25 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20211225_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltype',
            name='fuels_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car'),
        ),
    ]
