# Generated by Django 3.0.6 on 2021-12-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_fueltype_fuels_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fuel_id',
            new_name='fuel_type_id',
        ),
        migrations.RenameField(
            model_name='fueltype',
            old_name='fuels_id',
            new_name='fuel_type_id',
        ),
    ]
