# Generated by Django 3.0.6 on 2021-12-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20211225_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueltype',
            name='fuel_id',
        ),
        migrations.AddField(
            model_name='fueltype',
            name='fuel_types_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Model'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='fuel_type_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
