# Generated by Django 3.0.6 on 2021-12-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20211225_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueltype',
            old_name='fuel_types_id',
            new_name='fuel_type_car',
        ),
        migrations.RemoveField(
            model_name='fueltype',
            name='fuel_type_id',
        ),
        migrations.AddField(
            model_name='fueltype',
            name='type',
            field=models.CharField(choices=[('gas', 'Gas'), ('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('electro', 'Electro')], default='diesel', max_length=40, verbose_name='Fuel type'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='fuel_type',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
