# Generated by Django 3.0.6 on 2021-12-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20211225_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueltype',
            options={},
        ),
    ]
