# Generated by Django 3.0.6 on 2021-12-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20211225_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueltype',
            options={'verbose_name': 'Fuel type', 'verbose_name_plural': 'Fuel types'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='fuel_type_id',
            new_name='fuel_type',
        ),
    ]
