# Generated by Django 3.0.6 on 2021-12-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20211225_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueltype',
            name='fuel_type_car_id',
        ),
    ]
