# Generated by Django 3.0.6 on 2021-12-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_remove_fueltype_fuel_type_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Brand'),
        ),
    ]
