version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'django_app'
    env_file:
      - .env
    volumes:
      - .:/application
    ports:
      - "8000:8000"
    networks:
      - app
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db_data: