# Generated by Django 3.0.6 on 2021-12-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('sold', 'Sold')], default='in_stock', max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
        ),
    ]
