# Generated by Django 3.0.6 on 2021-12-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_auto_20211227_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
