# Generated by Django 3.2.9 on 2021-12-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=30)),
                ('portion_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, choices=[('autumn', 'Autumn'), ('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer')], default='spring', max_length=30)),
                ('name_kitchen', models.CharField(choices=[('UA', 'Ukrainian'), ('ITA', 'Italian'), ('GER', 'German')], max_length=10)),
                ('dish_choices', models.ManyToManyField(to='project.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('contacts', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Restaurant title')),
                ('num_stars', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=30)),
                ('about', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.country')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.menu')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.staff')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status'], name='project_res_status_afabfb_idx'),
        ),
    ]
