# Generated by Django 3.0.6 on 2021-12-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'NewsLetter', 'verbose_name_plural': 'NewsLetters'},
        ),
    ]
